language: bash
sudo: required
addons:
  apt:
    packages:
      - shellcheck
      - ncurses-dev
      - libevent-dev
      - gcc
      - make
      - curl

branches:
    only:
        - master
        - develop
        - /^develop-.*/
        - /^bugfix.*/
        - /^feature.*/

matrix:
    include:
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=1.8 CASES=1,4,10,30,40,44,45
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=1.9 CASES=15,19,23,24,33,34,47,51,53
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=1.9a CASES=5,8,17,20,22,24,25,27,34,35,41,43,47,51
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.0 CASES=2,11,19,20,22,23,31,47,49
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.1 CASES=6,12,14,15,20,23,28,29,34,36,38,42,50
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.2 CASES=5,8,10,16,21,27,30,31,35,36,46
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.3 CASES=10,16,21,34,35,39,42,43,46,47
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.4 CASES=1,3,13,24,25,36,42,48,53
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.5 CASES=1,4,6,7,9,10,12,13,16,50,52
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.6 CASES=3,7,12,18,25,26,37,41,44,45,48,53
        - os: linux
          env: SH=bash SH_VERSION=4.0 TMUX_VERSION=2.7 CASES=5,13,15,25,32,40,46,48,49
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=1.8 CASES=8,14,16,18,26,27,29,41
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=1.9 CASES=2,5,10,27,29,37,38,42,45,46
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=1.9a CASES=2,9,12,16,19,28,29,36,38,48
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.0 CASES=3,5,7,9,10,13,36,37,45,46,48,51,52,53
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.1 CASES=1,3,21,25,26,35,43,47
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.2 CASES=3,6,18,19,20,23,24,32,34,37,39,40,43,49,50,52
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.3 CASES=5,11,13,17,28,31,38,41,44
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.4 CASES=2,8,12,14,19,20,22,26,30,32,35,39,47
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.5 CASES=3,11,23,29,30,31,37,45
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.6 CASES=4,6,11,14,15,17,19,21,23,32,33,38,40,43
        - os: linux
          env: SH=bash SH_VERSION=4.1 TMUX_VERSION=2.7 CASES=6,11,22,28,34,44,53
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=1.8 CASES=3,7,9,13,22,23,28,35,37,42
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=1.9 CASES=7,12,14,18,28,35,39,41,43,48,49
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=1.9a CASES=10,14,18,21,23,26,44,50,52
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.0 CASES=1,4,6,15,16,17,21,24,28,29,32,33,34,35,38,42
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.1 CASES=8,11,19,32,33,39,41,44,45,46,53
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.2 CASES=1,7,15,17,25,48
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.3 CASES=1,20,22,26,27,36
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.4 CASES=6,9,10,15,16,27,28,33,38,40,49
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.5 CASES=2,5,8,14,17,21,25,32,41,42,53
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.6 CASES=2,8,22,27,29,30,31,34,47
        - os: linux
          env: SH=bash SH_VERSION=4.2 TMUX_VERSION=2.7 CASES=4,9,16,19,20,24,26,29,30,43,50,51
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=1.8 CASES=12,21,34,38,43
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=1.9 CASES=3,8,11,13,22,25,30,32,36,40,50,52
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=1.9a CASES=1,6,11,15,32,37,39,40,42,45,46,53
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.0 CASES=18,26,43,44
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.1 CASES=4,7,9,13,16,17,22,24,27,37,40
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.2 CASES=2,12,14,26,28,33,38,42,44,45,47,51
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.3 CASES=3,4,8,9,12,14,15,18,19,23,24,25,30,33,40,48
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.4 CASES=4,7,21,23,29,37,41,45,50,51
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.5 CASES=15,19,22,24,35,36,39,40,43,46,51
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.6 CASES=5,9,10,16,20,28,49,51
        - os: linux
          env: SH=bash SH_VERSION=4.3 TMUX_VERSION=2.7 CASES=2,8,17,21,27,31,33,35,41,45,47,52
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=1.8 CASES=5,11,15,17,19,20,24,25,33,36,39,46,47,48
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=1.9 CASES=1,4,6,9,16,17,20,21,26,31,44
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=1.9a CASES=3,4,7,13,30,31,33,49
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.0 CASES=8,12,14,25,27,30,39,40,41,50
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.1 CASES=2,5,10,18,30,31,48,49,51,52
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.2 CASES=4,9,11,13,22,29,41,53
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.3 CASES=7,29,32,37,45
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.4 CASES=5,11,17,18,31,34,43,44,46,52
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.5 CASES=18,20,26,27,28,33,34,38,44,47,48,49
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.6 CASES=1,13,24,35,36,39,42,46,50,52
        - os: linux
          env: SH=bash SH_VERSION=4.4 TMUX_VERSION=2.7 CASES=1,3,7,10,12,14,18,23,36,37,38,39,42


before_script:
  - export TMPDIR=$TRAVIS_BUILD_DIR/tmp
  - mkdir -p $TMPDIR
    # Remove default tmux
  - if which tmux ;then sudo mv -f `which tmux` `which tmux`.bak ;fi
  - ( cd "$TMPDIR" && curl -L "https://github.com/tmux/tmux/releases/download/${TMUX_VERSION}/tmux-${TMUX_VERSION}.tar.gz" | tar zxv && cd tmux-${TMUX_VERSION} && ./configure --prefix=${TMPDIR}; make && sudo make install )
  - if [[ "$SH" == "bash" && "$SH_VERSION" != "default" ]];then (cd "$TMPDIR" && curl "http://ftp.gnu.org/gnu/bash/bash-${SH_VERSION}.tar.gz" | tar xvz && cd bash* && ./configure; make && sudo make install && sudo mv /bin/bash /bin/bash.old && sudo cp ./bash /bin/bash ) ;fi
  - printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"
  - $SH ./test/test_generator.sh "${CASES}" > ./test/cases_pairwise.sh

script:
  - shellcheck ./bin/xpanes
  - TRAVIS_BUILD_DIR="${TRAVIS_BUILD_DIR}" $SH ./test/cases_pairwise.sh
