name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -d ./bin/xpanes

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
          - bash: "3.2"
            tmux: "1.8"
            cases: 8,9,17,23,25,30,35,41,62,63
          - bash: "3.2"
            tmux: "1.9"
            cases: 1,4,5,12,17,25,44,69,71,79
          - bash: "3.2"
            tmux: "1.9a"
            cases: 10,13,15,17,18,27,29,39,45,48,59,65,80,81,82,83
          - bash: "3.2"
            tmux: "2.0"
            cases: 10,16,31,34,42,48,50,53,54,59,72,73,81,85
          - bash: "3.2"
            tmux: "2.1"
            cases: 3,11,13,19,22,23,41,42,43,46,71,72,79,85
          - bash: "3.2"
            tmux: "2.2"
            cases: 2,4,16,22,24,31,42,57,69,72,77,84
          - bash: "3.2"
            tmux: "2.3"
            cases: 7,23,24,25,32,35,44,84
          - bash: "3.2"
            tmux: "2.4"
            cases: 6,14,15,33,42,45,49,52,69,84
          - bash: "3.2"
            tmux: "2.5"
            cases: 1,5,10,16,18,23,39,40,45,47,58,59,83
          - bash: "3.2"
            tmux: "2.6"
            cases: 5,15,18,32,37,40,42,43,44,52,55,78,83
          - bash: "3.2"
            tmux: "2.7"
            cases: 2,9,20,21,26,28,34,35,36,37,46,57,60,67,68,71
          - bash: "3.2"
            tmux: "2.8"
            cases: 5,6,9,12,14,20,26,37,38,40,63,66,70
          - bash: "3.2"
            tmux: "2.9"
            cases: 3,12,19,56,58,64,65,74,76,77,78
          - bash: "3.2"
            tmux: "2.9a"
            cases: 4,10,11,34,40,48,51,61,66,75,83,85
          - bash: "4.0"
            tmux: "1.8"
            cases: 1,5,7,36,38,59,69,83
          - bash: "4.0"
            tmux: "1.9"
            cases: 11,18,21,27,30,43,51,58,70,81
          - bash: "4.0"
            tmux: "1.9a"
            cases: 2,5,12,14,19,25,33,73,84
          - bash: "4.0"
            tmux: "2.0"
            cases: 2,13,22,26,33,49,58,71,80
          - bash: "4.0"
            tmux: "2.1"
            cases: 26,27,29,35,44,47,48,53,56,63,78,80
          - bash: "4.0"
            tmux: "2.2"
            cases: 1,3,10,17,26,27,50,53,62,70,83
          - bash: "4.0"
            tmux: "2.3"
            cases: 3,11,12,13,14,17,31,36,37,40,41,47,65,67,68
          - bash: "4.0"
            tmux: "2.4"
            cases: 9,19,35,63,65,73,80,81,85
          - bash: "4.0"
            tmux: "2.5"
            cases: 6,8,15,22,27,28,46,49,52,56,57,66,81
          - bash: "4.0"
            tmux: "2.6"
            cases: 1,8,9,10,19,20,22,29,30,34,47,54,56,60,61,64,79,82
          - bash: "4.0"
            tmux: "2.7"
            cases: 1,3,4,33,39,45,65,72,73,78
          - bash: "4.0"
            tmux: "2.8"
            cases: 3,10,21,24,25,29,42,45,46,47,71,77
          - bash: "4.0"
            tmux: "2.9"
            cases: 10,15,38,39,40,42,44,51,75,79,82
          - bash: "4.0"
            tmux: "2.9a"
            cases: 3,13,16,21,23,24,28,32,43,55,62,63,69,72,74,76,77,78,84
          - bash: "4.1"
            tmux: "1.8"
            cases: 13,22,24,34,42,43,47,70,71,80,82,84
          - bash: "4.1"
            tmux: "1.9"
            cases: 8,15,22,23,38,40,41,73
          - bash: "4.1"
            tmux: "1.9a"
            cases: 7,9,30,32,34,43,52,62,72,78
          - bash: "4.1"
            tmux: "2.0"
            cases: 3,9,12,20,24,25,43,44,62,63,66,70
          - bash: "4.1"
            tmux: "2.1"
            cases: 1,14,15,21,32,34,50,52,54,55,65,83
          - bash: "4.1"
            tmux: "2.2"
            cases: 33,36,51,56,58,63,66
          - bash: "4.1"
            tmux: "2.3"
            cases: 20,34,45,58,61,66,73
          - bash: "4.1"
            tmux: "2.4"
            cases: 2,10,24,25,29,30,37,38,46,48,66,68,71,82,83
          - bash: "4.1"
            tmux: "2.5"
            cases: 7,14,17,32,35,38,53,73,79
          - bash: "4.1"
            tmux: "2.6"
            cases: 4,6,11,14,23,27,39,67
          - bash: "4.1"
            tmux: "2.7"
            cases: 14,18,19,50,52,55,56,69,70,74,76,77,85
          - bash: "4.1"
            tmux: "2.8"
            cases: 4,8,18,28,39,51,57,59,75,80,81,83
          - bash: "4.1"
            tmux: "2.9"
            cases: 5,13,16,17,18,21,24,26,28,41,48,49,53,60,72,83,84
          - bash: "4.1"
            tmux: "2.9a"
            cases: 5,12,18,19,22,29,31,33,35,37,38,39,46,64,65
          - bash: "4.2"
            tmux: "1.8"
            cases: 10,11,19,20,21,26,28,48,56,73,77
          - bash: "4.2"
            tmux: "1.9"
            cases: 6,7,13,29,32,35,46,47,55,56,65,83,84
          - bash: "4.2"
            tmux: "1.9a"
            cases: 11,22,23,42,49,51,66,79
          - bash: "4.2"
            tmux: "2.0"
            cases: 6,18,23,41,45,55,56,57,65
          - bash: "4.2"
            tmux: "2.1"
            cases: 2,24,25,31,38,39,40,58,62,70,73
          - bash: "4.2"
            tmux: "2.2"
            cases: 6,12,14,19,37,39,41,44,55,85
          - bash: "4.2"
            tmux: "2.3"
            cases: 5,9,19,26,28,33,43,70,71,79,80,82
          - bash: "4.2"
            tmux: "2.4"
            cases: 3,7,17,20,22,23,27,28,34,47,50,51,54,57,67,72
          - bash: "4.2"
            tmux: "2.5"
            cases: 12,50,60,78,82
          - bash: "4.2"
            tmux: "2.6"
            cases: 2,7,13,17,31,41,46,50,59,68,72,75
          - bash: "4.2"
            tmux: "2.7"
            cases: 5,8,16,30,32,40,42,48,49,58,59,64
          - bash: "4.2"
            tmux: "2.8"
            cases: 13,33,35,36,52,56,61,73,76,82
          - bash: "4.2"
            tmux: "2.9"
            cases: 1,2,4,20,35,36,52,63,66,69,73
          - bash: "4.2"
            tmux: "2.9a"
            cases: 8,15,20,27,30,44,53,54,57,71,74,81
          - bash: "4.3"
            tmux: "1.8"
            cases: 14,31,37,65,79
          - bash: "4.3"
            tmux: "1.9"
            cases: 3,10,14,16,19,34,53,77,85
          - bash: "4.3"
            tmux: "1.9a"
            cases: 1,3,8,16,35,37,40,41,44,47,53,55,56,63,69,70
          - bash: "4.3"
            tmux: "2.0"
            cases: 1,4,7,8,21,27,32,39,51,69,82,83
          - bash: "4.3"
            tmux: "2.1"
            cases: 5,8,17,18,28,45,51,57,66,77,84
          - bash: "4.3"
            tmux: "2.2"
            cases: 8,11,21,23,38,40,43,47,54,59,73,78
          - bash: "4.3"
            tmux: "2.3"
            cases: 15,16,22,29,30,46,48,49,59,72
          - bash: "4.3"
            tmux: "2.4"
            cases: 8,12,16,31,39,40,56,58,59,60,61
          - bash: "4.3"
            tmux: "2.5"
            cases: 3,20,21,24,25,30,41,44,63,68,70,77,80,84,85
          - bash: "4.3"
            tmux: "2.6"
            cases: 12,26,28,33,36,38,48,51,69,71,80,81
          - bash: "4.3"
            tmux: "2.7"
            cases: 7,11,13,15,24,25,44,54,63,66,79,80
          - bash: "4.3"
            tmux: "2.8"
            cases: 15,41,50,64,65,68,69,74,76,84
          - bash: "4.3"
            tmux: "2.9"
            cases: 6,9,11,27,30,33,34,37,43,45,47,50,54,57,61,62,67,75,80
          - bash: "4.3"
            tmux: "2.9a"
            cases: 2,36,41,42,52,59,79
          - bash: "4.4"
            tmux: "1.8"
            cases: 3,4,12,18,27,40,44,45,81
          - bash: "4.4"
            tmux: "1.9"
            cases: 31,33,36,37,39,42,48,49,59,66,78,82
          - bash: "4.4"
            tmux: "1.9a"
            cases: 4,6,21,24,28,31,46,54,57,58
          - bash: "4.4"
            tmux: "2.0"
            cases: 5,15,19,28,29,30,36,37,38,47,52
          - bash: "4.4"
            tmux: "2.1"
            cases: 4,7,9,10,16,36,49,59,81,82
          - bash: "4.4"
            tmux: "2.2"
            cases: 9,15,18,20,35,49,52,71,79,81
          - bash: "4.4"
            tmux: "2.3"
            cases: 1,4,18,38,39,60,77,78,81,83
          - bash: "4.4"
            tmux: "2.4"
            cases: 1,11,13,26,36,53,55,77,78
          - bash: "4.4"
            tmux: "2.5"
            cases: 2,9,13,26,33,34,37,42,43,51,54,61,67,69,72
          - bash: "4.4"
            tmux: "2.6"
            cases: 16,21,25,45,49,53,57,63,65,66,70,73,74,76,84
          - bash: "4.4"
            tmux: "2.7"
            cases: 17,22,23,29,31,38,41,43,64,75,84
          - bash: "4.4"
            tmux: "2.8"
            cases: 1,2,16,22,27,34,43,54,62,72,79,85
          - bash: "4.4"
            tmux: "2.9"
            cases: 8,25,29,31,32,68,70,71,85
          - bash: "4.4"
            tmux: "2.9a"
            cases: 7,14,17,25,26,49,50,56,60,67,70,80,82
          - bash: "5.0"
            tmux: "1.8"
            cases: 15,16,29,39,46,49,58,66,72,78
          - bash: "5.0"
            tmux: "1.9"
            cases: 2,9,20,24,26,28,45,50,52,54,57,62,63,72,80
          - bash: "5.0"
            tmux: "1.9a"
            cases: 20,26,36,38,50,71,77,85
          - bash: "5.0"
            tmux: "2.0"
            cases: 11,14,17,35,40,46,77,78,79,84
          - bash: "5.0"
            tmux: "2.1"
            cases: 6,12,20,30,33,37,69
          - bash: "5.0"
            tmux: "2.2"
            cases: 5,7,13,25,28,29,30,32,34,45,46,48,65,80,82
          - bash: "5.0"
            tmux: "2.3"
            cases: 8,10,21,27,42,56,69
          - bash: "5.0"
            tmux: "2.4"
            cases: 4,5,18,21,32,41,43,44,70,79
          - bash: "5.0"
            tmux: "2.5"
            cases: 4,11,19,29,31,36,48,55,65,71
          - bash: "5.0"
            tmux: "2.6"
            cases: 3,24,35,58,77,85
          - bash: "5.0"
            tmux: "2.7"
            cases: 6,10,12,27,47,51,53,61,81,82,83
          - bash: "5.0"
            tmux: "2.8"
            cases: 7,11,17,19,23,30,31,32,44,48,49,53,55,58,60,67,78
          - bash: "5.0"
            tmux: "2.9"
            cases: 7,14,22,23,46,55,59,64,74,75,81
          - bash: "5.0"
            tmux: "2.9a"
            cases: 1,6,9,45,47,58,68,73,76

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit testing
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/cases_smoke.sh'
