name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d ./bin/xpanes

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
###START_INSERT###
          - bash: "3.2"
            tmux: "1.8"
            cases: 8,10,12,24,25,48,70
          - bash: "3.2"
            tmux: "1.9"
            cases: 1,7,12,21,26,28,37,50,51,55,71,72,76,78
          - bash: "3.2"
            tmux: "1.9a"
            cases: 20,23,28,30,32,62,69,72,76,81
          - bash: "3.2"
            tmux: "2.0"
            cases: 11,21,22,27,30,35,36,38,41,45,62,65,72
          - bash: "3.2"
            tmux: "2.1"
            cases: 2,19,28,38,39,61,64,70,77,80,81
          - bash: "3.2"
            tmux: "2.2"
            cases: 23,26,33,42,43,48,49,58,68,78,79
          - bash: "3.2"
            tmux: "2.3"
            cases: 8,9,17,31,41,42,48,59,79,82
          - bash: "3.2"
            tmux: "2.4"
            cases: 8,14,40,43,49,56,65,71,78,79,84
          - bash: "3.2"
            tmux: "2.5"
            cases: 3,13,15,18,20,22,24,32,54,55,62,71
          - bash: "3.2"
            tmux: "2.6"
            cases: 2,6,10,25,26,29,46,47,49,69,75,84
          - bash: "3.2"
            tmux: "2.7"
            cases: 4,11,14,27,33,35,52,74
          - bash: "3.2"
            tmux: "2.8"
            cases: 7,32,35,37,44,48,51,53,55,57,78,83
          - bash: "3.2"
            tmux: "2.9"
            cases: 2,5,16,19,25,26,27,39,40,42,50,57,60,64,72,77
          - bash: "3.2"
            tmux: "2.9a"
            cases: 15,18,31,34,38,44,53,63,66,67,70,73,83
          - bash: "4.0"
            tmux: "1.8"
            cases: 9,13,23,34,37,58,69,82
          - bash: "4.0"
            tmux: "1.9"
            cases: 4,24,34,43,52,61,65,84
          - bash: "4.0"
            tmux: "1.9a"
            cases: 6,19,31,33,44,45,47,49,55
          - bash: "4.0"
            tmux: "2.0"
            cases: 2,3,4,5,10,17,20,46,48,54,64,78,80
          - bash: "4.0"
            tmux: "2.1"
            cases: 3,4,11,25,36,40,42,46,49,72,79
          - bash: "4.0"
            tmux: "2.2"
            cases: 2,3,5,30,35,47,50,51,53,55,71,72,81,84
          - bash: "4.0"
            tmux: "2.3"
            cases: 4,15,16,22,23,26,28,33,38,69,70,77,81,83
          - bash: "4.0"
            tmux: "2.4"
            cases: 2,3,13,15,17,23,30,45,54,60
          - bash: "4.0"
            tmux: "2.5"
            cases: 6,12,16,36,66,81
          - bash: "4.0"
            tmux: "2.6"
            cases: 1,21,37,41,72,74,76
          - bash: "4.0"
            tmux: "2.7"
            cases: 5,6,8,24,28,29,39,49,54,57,63,68,73,76,78,79,82
          - bash: "4.0"
            tmux: "2.8"
            cases: 8,18,20,21,22,27,28,40,46
          - bash: "4.0"
            tmux: "2.9"
            cases: 6,7,14,22,24,32,35,41,46,49,52,67,75
          - bash: "4.0"
            tmux: "2.9a"
            cases: 13,24,43,56,59,62,65,77,82
          - bash: "4.1"
            tmux: "1.8"
            cases: 7,16,19,20,29,33,35,62,71
          - bash: "4.1"
            tmux: "1.9"
            cases: 16,17,23,30,41,44,49,83
          - bash: "4.1"
            tmux: "1.9a"
            cases: 9,17,39,48,52,54,78,82
          - bash: "4.1"
            tmux: "2.0"
            cases: 25,28,56,57,68,70,81
          - bash: "4.1"
            tmux: "2.1"
            cases: 5,15,17,26,27,34,52,58,84
          - bash: "4.1"
            tmux: "2.2"
            cases: 1,4,15,20,24,27,31,36,38,39,44,46,54,65
          - bash: "4.1"
            tmux: "2.3"
            cases: 2,6,10,12,18,19,25,32,43,45,55
          - bash: "4.1"
            tmux: "2.4"
            cases: 1,7,25,34,44,67,69,81
          - bash: "4.1"
            tmux: "2.5"
            cases: 8,10,38,50,56,68,80,82
          - bash: "4.1"
            tmux: "2.6"
            cases: 11,13,17,23,27,28,30,31,53,54,58,59,63,77
          - bash: "4.1"
            tmux: "2.7"
            cases: 3,12,21,26,30,43,44,45,47,53,64,65,66,81
          - bash: "4.1"
            tmux: "2.8"
            cases: 6,14,15,42,50,58,66,72,73,79,84
          - bash: "4.1"
            tmux: "2.9"
            cases: 3,13,21,36,37,44,51,55,61,74,75,76,80
          - bash: "4.1"
            tmux: "2.9a"
            cases: 12,22,25,27,40,41,42,60,71
          - bash: "4.2"
            tmux: "1.8"
            cases: 11,14,40,44,45,47,76,80
          - bash: "4.2"
            tmux: "1.9"
            cases: 2,3,5,13,15,22,27,29,31,32,35,38,39,46,57,79,82
          - bash: "4.2"
            tmux: "1.9a"
            cases: 1,10,11,15,16,35,42,43,61,68,77,79
          - bash: "4.2"
            tmux: "2.0"
            cases: 6,7,13,19,23,29,40,44,50,61
          - bash: "4.2"
            tmux: "2.1"
            cases: 9,14,18,20,21,30,35,41,71
          - bash: "4.2"
            tmux: "2.2"
            cases: 8,18,22,29,37,52,56,83
          - bash: "4.2"
            tmux: "2.3"
            cases: 7,11,20,36,57,68,72
          - bash: "4.2"
            tmux: "2.4"
            cases: 5,10,21,29,37,53,66,68,83
          - bash: "4.2"
            tmux: "2.5"
            cases: 28,30,33,34,39,47,49,64,69,70
          - bash: "4.2"
            tmux: "2.6"
            cases: 3,7,8,22,35,39,43,51,52,55,60,63,64,73,83
          - bash: "4.2"
            tmux: "2.7"
            cases: 2,9,16,18,25,31,32,46,48,56,62,67,70,84
          - bash: "4.2"
            tmux: "2.8"
            cases: 4,5,12,16,17,23,24,25,26,33,59,60,68,81
          - bash: "4.2"
            tmux: "2.9"
            cases: 9,38,58,65,75
          - bash: "4.2"
            tmux: "2.9a"
            cases: 1,5,7,8,10,26,28,33,37,45,47,54,57,64,68,69,72,74,78
          - bash: "4.3"
            tmux: "1.8"
            cases: 2,15,17,26,28,38,41,42,55,57,68,78
          - bash: "4.3"
            tmux: "1.9"
            cases: 8,9,14,36,45,47,56,58,62
          - bash: "4.3"
            tmux: "1.9a"
            cases: 4,7,21,22,27,40,53,57,64,65,80
          - bash: "4.3"
            tmux: "2.0"
            cases: 1,9,18,34,47,82,83,84
          - bash: "4.3"
            tmux: "2.1"
            cases: 1,7,12,13,16,23,32,37,43,44,48,50,51,83
          - bash: "4.3"
            tmux: "2.2"
            cases: 13,17,25,32,34,40,76,80
          - bash: "4.3"
            tmux: "2.3"
            cases: 14,21,29,37,39,40,46,58,65,67,71
          - bash: "4.3"
            tmux: "2.4"
            cases: 9,11,16,22,24,26,31,33,39,41,46,47,52,55,57,59,70,72
          - bash: "4.3"
            tmux: "2.5"
            cases: 1,4,5,9,25,27,31,35,42,43,44,45,53,58,77
          - bash: "4.3"
            tmux: "2.6"
            cases: 18,32,33,38,40,42,67,71,78,81,82
          - bash: "4.3"
            tmux: "2.7"
            cases: 10,34,36,41,51,60,69,75
          - bash: "4.3"
            tmux: "2.8"
            cases: 3,29,31,41,47,54,56,61,64,74
          - bash: "4.3"
            tmux: "2.9"
            cases: 10,11,17,20,23,45,62,63,66,71,73,79,81,82
          - bash: "4.3"
            tmux: "2.9a"
            cases: 3,6,9,14,17,19,30,49,52,55,79,84
          - bash: "4.4"
            tmux: "1.8"
            cases: 6,22,27,30,39,43,46
          - bash: "4.4"
            tmux: "1.9"
            cases: 18,20,25,40,42,54,80,81
          - bash: "4.4"
            tmux: "1.9a"
            cases: 3,8,12,13,29,34,37,41,50,51,56,71,84
          - bash: "4.4"
            tmux: "2.0"
            cases: 8,12,14,16,24,26,32,33,37,49,51,52,53,69,76
          - bash: "4.4"
            tmux: "2.1"
            cases: 8,10,29,31,33,45,55,65,68,78
          - bash: "4.4"
            tmux: "2.2"
            cases: 7,11,19,45,61,62,64,69,77
          - bash: "4.4"
            tmux: "2.3"
            cases: 3,24,27,35,44,47,60,64,76,80
          - bash: "4.4"
            tmux: "2.4"
            cases: 6,18,28,36,42,48,50,51,80
          - bash: "4.4"
            tmux: "2.5"
            cases: 2,7,11,14,19,21,37,41,48,59,65,76,79,83
          - bash: "4.4"
            tmux: "2.6"
            cases: 4,5,14,15,19,24,34,50,56,57,66,73
          - bash: "4.4"
            tmux: "2.7"
            cases: 13,15,17,23,38,40,42,58,59,71,72,74,77
          - bash: "4.4"
            tmux: "2.8"
            cases: 2,9,10,11,30,36,39,52,62,65,67,69,70,71,82
          - bash: "4.4"
            tmux: "2.9"
            cases: 1,4,12,15,28,33,34,43,47,48,53,63,68,69
          - bash: "4.4"
            tmux: "2.9a"
            cases: 11,16,21,32,36,39,61,75,81
          - bash: "5.0"
            tmux: "1.8"
            cases: 3,4,18,21,36,61,64,65,72,77,79,81,83
          - bash: "5.0"
            tmux: "1.9"
            cases: 6,10,11,19,33,48,53,64,68,69,70,77
          - bash: "5.0"
            tmux: "1.9a"
            cases: 2,5,14,18,24,25,26,36,38,46,58,70,83
          - bash: "5.0"
            tmux: "2.0"
            cases: 15,31,39,42,43,55,58,71,77,79
          - bash: "5.0"
            tmux: "2.1"
            cases: 6,22,24,47,53,54,56,57,62,69,76,82
          - bash: "5.0"
            tmux: "2.2"
            cases: 6,9,10,12,14,16,21,28,41,57,70,82
          - bash: "5.0"
            tmux: "2.3"
            cases: 13,30,34,66,78
          - bash: "5.0"
            tmux: "2.4"
            cases: 4,12,19,20,27,32,35,38,58,62,64,76,77,82
          - bash: "5.0"
            tmux: "2.5"
            cases: 17,23,26,29,40,46,51,52,57,60,67,72,78,84
          - bash: "5.0"
            tmux: "2.6"
            cases: 9,12,16,20,36,44,45,48,62,65,68,70,79,80
          - bash: "5.0"
            tmux: "2.7"
            cases: 1,7,19,20,22,37,50,55,80,83
          - bash: "5.0"
            tmux: "2.8"
            cases: 1,13,19,34,38,43,45,49,63,75,76,77,80
          - bash: "5.0"
            tmux: "2.9"
            cases: 8,18,29,30,31,54,56,59,70,78,83,84
          - bash: "5.0"
            tmux: "2.9a"
            cases: 2,4,20,23,29,35,46,48,50,51,58,73,74,76,80
###END_INSERT###

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit test
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/unit.sh'

    - name: Scenario test
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test/cases_pairwise.sh'
