name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -d ./bin/xpanes

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bash: 3.2
            tmux: 1.8
        # bash: [3.2,4.0,4.1,4.2,4.3,4.4,5.0]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit testing
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/cases_smoke.sh'
        # script -e -c /bin/bash -c 'export TERM=xterm; tmux -S socket new-session -d; tmux -S socket send-keys "seq 10 > hoge" C-m; sleep 1; cat hoge; tmux -S socket attach'
