name: test

on:
  push:
    branches:
      - master
      - develop
      - /^develop-.*/
      - /^bugfix.*/
      - /^feature.*/
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 8 * * 6" # UTC 08:00 (Sat)

jobs:

  linux-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        shell: [3.2,4.0,4.1,4.2,4.3,4.4,5.0]
        tmux: [1.8,1.9,1.9a,2.0,2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9,2.9a,3.0,3.0a]


    steps:
    - uses: actions/checkout@v2
      #     - name: Checkout submodules
      #       run:  git submodule update --init --recursive

    - name: Install dependency
      run: |
        echo shell=${{matrix.shell}}
        echo tmux=${{matrix.tmux}}
        #    - name: Run tests
        #      run: ./test.sh
